server:
  port: 8081

application:
  crud-server-url: http://84.252.137.151:8082/
  keycloak-url-xforward: 84.252.137.151/:8080
  log-body-limit: 128
  keycloak-register-client-id: admin-cli
  keycloak-register-client-secret: 5ee6596a-27c8-4452-ab22-d32162442733

keycloak:
  auth-server-url: http://84.252.137.151:8080/auth/
  realm: balance-tracker
  resource: balance-tracker-common
  public-client: true
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: 8ccc9d29-726a-40fc-baa9-6b87f9bbfbaf

spring:
  main:
    allow-bean-definition-overriding: true