server:
  port: 8081

application:
  crud-server-url: http://130.193.43.233:8082/
  keycloak-url-xforward: 130.193.43.233/:8080
  log-body-limit: 128
  keycloak-register-client-id: admin-cli
  keycloak-register-client-secret: 5ee6596a-27c8-4452-ab22-d32162442733

keycloak:
  auth-server-url: http://130.193.43.233:8080/auth/
  realm: balance-tracker
  resource: balance-tracker-common
  public-client: true
  ssl-required: NONE
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: 8ccc9d29-726a-40fc-baa9-6b87f9bbfbaf

spring:
  main:
    allow-bean-definition-overriding: true