# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD B-T-Gateway main
env:
  DOCKER_IMAGE_NAME: "artemyyours/balance-tracker-gateway:master"
  PORT_TO_MAP: "8081:8081"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch...
        uses: actions/checkout@v2

      - name: Gradle Build...
        run: gradle build

      - name: Set up QEMU...
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx...
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub...
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push...
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Stopping and removing ld image...
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SECRET }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script:
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ env.DOCKER_IMAGE_NAME }} --format="{{.ID}}")) &
            docker image rm ${{ env.DOCKER_IMAGE_NAME }} &
            exit
      - name: Pulling and starting new image...
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SECRET }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script:
            docker run -p ${{ env.PORT_TO_MAP }} ${{ env.DOCKER_IMAGE_NAME }} &
            exit
